version: 2

sources:
  - name: stripe
    tables:
      - name: payment
        columns:
          - name: id
            data_type: integer
          - name: orderid
            data_type: integer
          - name: paymentmethod
            data_type: text
          - name: status
            data_type: text
          - name: amount
            data_type: integer
          - name: created
            data_type: date

