version: 2

sources:
  - name: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            data_type: integer
          - name: first_name
            data_type: text
          - name: last_name
            data_type: text

      - name: orders
        columns:
          - name: id
            data_type: integer
          - name: user_id
            data_type: integer
          - name: order_date
            data_type: date
          - name: status
            data_type: text